services:
  backend:
    build:      
      dockerfile: SalesService.Api/Dockerfile
      context: .
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Release
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=SalesServiceDb;Username=postgres;Password=random@SECURE1234! 
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:15
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 15s
      timeout: 5s
      retries: 2
    environment:
      - POSTGRES_DB=SalesServiceDb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=random@SECURE1234!
    ports:
      - "5432:5432"
  