version: '3.8'

services:
  sales_service:
    build:
      context: .
      dockerfile: SalesService.Api/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=localhost;Database=SalesServiceDb;Username=superadmin;Password=random@SECURE1234!
    depends_on:
      - postgres_db

  postgres_db:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_DB=SalesServiceDb
      - POSTGRES_USER=superadmin
      - POSTGRES_PASSWORD=random@SECURE1234!
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: